export const IPC_CHANNELS = {
  applicationGetInfo: "application:get-info",
  configurationGet: "configuration:get",
  configurationChoose: "configuration:choose",
  authenticationPrepare: "authentication:prepare",
  authenticationSignIn: "authentication:sign-in",
  authenticationCancel: "authentication:cancel",
  translationCreateSecret: "translation:create-secret",
  recordingStart: "recording:start",
  recordingAppend: "recording:append",
  recordingStop: "recording:stop",
  recordingExport: "recording:export",
  recordingDiscard: "recording:discard",
  appEvent: "app:event",
} as const;
